preload = /home/sean/pictures/wallpapers/purple-flower.jpg
#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = DP-2,/home/sean/pictures/wallpapers/purple-flower.jpg
#if more than one monitor in use, can load a 2nd image
wallpaper = DP-3,/home/sean/pictures/wallpapers/purple-flower.jpg
splash = false
