# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/181db0ff-1e8d-4846-bc07-5be85d0b9ef0";
      fsType = "ext4";
    };

  fileSystems."/var/lib/kubelet/pods/4b2b3f42-f80a-47c6-ab9e-f0ed0cda4519/volumes/kubernetes.io~projected/kube-api-access-xs5f8" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/60f5f9fd-e65a-4017-a71b-f11ae4b4abed/volumes/kubernetes.io~projected/kube-api-access-ftz2x" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/8f38aad9-6d96-4eff-92bf-9ed1863497d2/volumes/kubernetes.io~projected/kube-api-access-9jrtv" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/b94bb080-71b5-4967-9f66-443ccfa06538/volumes/kubernetes.io~projected/kube-api-access-ftbng" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/135C-04AE";
      fsType = "vfat";
    };

  fileSystems."/ssd" =
    { device = "/dev/disk/by-uuid/3abd3c47-d49a-4132-8049-246be6a0e61c";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4e27be2b-9329-484a-91ba-7f7f81c15db5"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
